### PR TITLE
Fix for https://github.com/devopsfolks/podam/issues/234

### PR DESCRIPTION
**Pull request by Otanikotani**
This is one possible solution to fix the bug with raw ArrayList. This adds type manufacturers for ArrayList, LinkedList and HashSet, so those manufacturers will take precedence over the Cloneable manufacturer.

### CODE REVIEW

**Comment by daivanov** [comment]
And then someone will try to produce non-generic Vector and this won't work :)

**Comment by daivanov** [comment]
Well, I can merge your tests, but now this is not super easy due to conflict in AbstractRandomDataProviderStrategy. Could you please amend your commit for this?

**Comment by Otanikotani** [comment]
> And then someone will try to produce non-generic Vector and this won't work :)

Yeah, you are right. Well, there is still a fallback with CollectionTypeManufacturer for other collection types, and of course someone who still uses Vector class is able to add the custom typemanufacturer. Maybe it will make them realize that those days are gone!

**Comment by daivanov** [comment]
Now Vector should be fine. The main problem here is that using ArrayList instead of List is a coupling problem as it imposes unnecessary constraint on a POJO's interface.

**Pull request closed without merging**
