### PR TITLE
Warning problems corrections + format corrections

### PR DESCRIPTION
**Pull request by dedece35**
My first commit before give you help on your project.
We use Podam on all our projects in my job in PagesJaunes (french famous website).

I specilly am interested to work on @Pattern annotation : we use it a lot.

### CODE REVIEW

**Comment by dedece35** [comment]
Sorry but I don't understand errors ...
with JDK 1.6 : all test are OK ("mvn clean verify")
with JDK 1.8 : all test are OK (Travis) => command launched OK : "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
with JDK 1.7 : errors with Travis ?! => command launched KO : "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
   mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
   The JAVA_HOME environment variable is not defined correctly
   This environment variable is needed to run this program
   NB: JAVA_HOME should point to a JDK not a JRE

With 1.7 environment, it seems to have a pb with JAVA_HOME variable, no ?

**Comment by daivanov** [comment]
Thank you for you patch. _oraclejdk7_ doesn't seem to be supported by Travis any more and they suggest to switch to _openjdk7_ instead.

**Comment by dedece35** [comment]
OK. thanks for your explain.
Do you think you could accept my PullRequest ?

**Comment by daivanov** [comment]
Yes, but could you incorporate the fix in _.travis.yml_ and could you please make a pull request against _develop_ branch. Also I don't think double empty lines separating methods is a formatting problem. Rather this is a good thing helping to avoid conflicts sometimes.

**Comment by dedece35** [comment]
OK. I will correct these things.
Sorry, it's my automatic formatter deleted "double empty lines". I will disable my automatic formatter for this project :)

**Comment by dedece35** [comment]
I cancel this pull request and submit new PR.

**Pull request closed without merging**
