### PR TITLE
closes #205

### LINKED ISSUE #205: Podam fails to select right annotation in case a field has multiple annotations
A sample POJO

    public class Test {

        @PodamStringValue(length = 3)
        @Length(min = 3, max = 3)
        String field;
    }

### PR DESCRIPTION
**Pull request by maxdidato**

### CODE REVIEW

**Comment by daivanov** [comment]
Can this patch be significantly smaller than 20000 lines?

**Comment by maxdidato** [comment]
Most of the lines are test fixtures. The production code is actually very small. 
I have also added another annotation @IgnoreNonPodamAnnotations which will get rid of any non Podam annotations, this is an easy fix when some annotations clash

**Comment by daivanov** [comment]
I'm sorry, but I cannot merge patch changing 2061 lines mostly because of white spaces as is.

**Comment by maxdidato** [comment]
No problem, I'll tidy it up

**Comment by daivanov** [comment]
Could you please split commit 1d7606e4d2a8699bed36b7e9d2ce834a2423cc3a into part with test and without?

**Comment by daivanov** [comment]
Partially merged.

**Comment by daivanov** [comment]
If you want, you can give me your real name and/or email for inclusion into pom.xml's contributors section.

**Comment by maxdidato** [comment]
Massimiliano Di Dato didatomax@gmail.com

So you basically cherry picked the changes, no more tidying up required?

**Comment by daivanov** [comment]
Yes, cherry-picked and then amended. Large patches are hard to review and they pollute a sources history.

**Comment by maxdidato** [comment]
Hi @daivanov . Thanks for including me in the contributor lists on the pom.xml in master. Could you please also amend my details with the one I posted previously on this thread?

And maybe adding me to the contributors list. 
Thanks

**Comment by daivanov** [comment]
I beg a pardon. I somehow missed your email. Now added.

**Comment by maxdidato** [comment]
Thanks

**Pull request closed without merging**
